'''
Purpose:
*
'''

###################
##### IMPORTS #####
###################

from enum import IntEnum, unique

#####################
##### MAP ENUMS #####
#####################

@unique
class MAP_ENUMS(IntEnum):
    spiral_mountain_main = 0x1,
    mumbos_mountain_main = 0x2,
    treasure_trove_cove_blubbers_ship = 0x5,
    treasure_trove_cove_nippers_shell = 0x6,
    treasure_trove_cove_main = 0x7,
    treasure_trove_cove_sandcastle = 0xA,
    clankers_cavern_main = 0xB,
    mumbos_mountain_termite_hill = 0xC,
    bubblegloop_swamp_main = 0xD,
    mumbos_mountain_mumbos_skull = 0xE,
    bubblegloop_swamp_mr_vile = 0x10,
    bubblegloop_swamp_tip_tup_chior = 0x11,
    gobis_valley_main = 0x12,
    gobis_valley_matching_puzzle = 0x13,
    gobis_valley_king_sandybutts_tomb = 0x14,
    gobis_valley_water_pyramid = 0x15,
    gobis_valley_rupee = 0x16,
    gobis_valley_jinxy = 0x1A,
    mad_monster_mansion_main = 0x1B,
    mad_monster_mansion_church_main = 0x1C,
    mad_monster_mansion_cellar = 0x1D,
    cutscene_intro = 0x1E,
    cutscene_n64_logo = 0x1F,
    cutscene_beach_ending_without_100_jiggies = 0x20,
    clankers_cavern_blowhole = 0x21,
    clankers_cavern_mouth_belly = 0x22,
    clankers_cavern_wonderwing = 0x23,
    mad_monster_mansion_tumblar = 0x24,
    mad_monster_mansion_well = 0x25,
    mad_monster_mansion_dining_room = 0x26,
    freezeezy_peak_main = 0x27,
    mad_monster_mansion_egg_room = 0x28,
    mad_monster_mansion_note_room = 0x29,
    mad_monster_mansion_red_feather_room = 0x2A,
    mad_monster_mansion_secret_church_room = 0x2B,
    mad_monster_mansion_bathroom = 0x2C,
    mad_monster_mansion_bedroom = 0x2D,
    mad_monster_mansion_honeycomb_room = 0x2E,
    mad_monster_mansion_drainpipe = 0x2F,
    mad_monster_mansion_mumbos_hut = 0x30,
    rusty_bucket_bay_main = 0x31,
    rusty_bucket_bay_engine_room = 0x34,
    rusty_bucket_bay_chump_warehouse = 0x35,
    rusty_bucket_bay_boat_room = 0x36,
    rusty_bucket_bay_chompa_container = 0x37,
    rusty_bucket_bay_boom_box_container = 0x38,
    rusty_bucket_bay_cabin_window = 0x39,
    rusty_bucket_bay_boss_boom_box_room = 0x3A,
    rusty_bucket_bay_boom_box_pipe = 0x3B,
    rusty_bucket_bay_kitchen_pipe = 0x3C,
    rusty_bucket_bay_navigation_window = 0x3D,
    rusty_bucket_bay_seaman_grublins_container = 0x3E,
    rusty_bucket_bay_captains_window = 0x3F,
    click_clock_wood_main_hub = 0x40,
    freezeezy_peak_igloo = 0x41,
    click_clock_wood_spring_main = 0x43,
    click_clock_wood_summer_main = 0x44,
    click_clock_wood_autumn_main = 0x45,
    click_clock_wood_winter_main = 0x46,
    bubblegloop_swamp_mumbos_skull = 0x47,
    freezeezy_peak_mumbos_skull = 0x48,
    click_clock_wood_spring_mumbos_skull = 0x4A,
    click_clock_wood_summer_mumbos_skull = 0x4B,
    click_clock_wood_autumn_mumbos_skull = 0x4C,
    click_clock_wood_winter_mumbos_skull = 0x4D,
    freezeezy_peak_christmas_tree = 0x53,
    click_clock_wood_summer_zubbas = 0x5A,
    click_clock_wood_spring_zubbas = 0x5B,
    click_clock_wood_autumn_zubbas = 0x5C,
    click_clock_wood_spring_nabnuts = 0x5E,
    click_clock_wood_summer_nabnuts = 0x5F,
    click_clock_wood_autumn_nabnuts = 0x60,
    click_clock_wood_winter_nabnuts = 0x61,
    click_clock_wood_winter_acorn_attic = 0x62,
    click_clock_wood_autumn_flooded_attic = 0x63,
    click_clock_wood_winter_flooded_attic = 0x64,
    click_clock_wood_spring_whipcracks = 0x65,
    click_clock_wood_summer_whipcracks = 0x66,
    click_clock_wood_autumn_whipcracks = 0x67,
    click_clock_wood_winter_whipcracks = 0x68,
    gruntildas_lair_mumbos_mountain_entrance = 0x69,
    gruntildas_lair_treasure_trove_cove_clankers_cavern_puzzles = 0x6A,
    gruntildas_lair_click_clock_wood_puzzle = 0x6B,
    gruntildas_lair_cauldron_pipe_room = 0x6C,
    gruntildas_lair_treasure_trove_cove_entrance = 0x6D,
    gruntildas_lair_gobis_valley_entrance = 0x6E,
    gruntildas_lair_freezeezy_peak_entrance = 0x6F,
    gruntildas_lair_clankers_cavern_entrance = 0x70,
    gruntildas_lair_pointing_grunty_statue = 0x71,
    gruntildas_lair_bubblegloop_swamp_entrance = 0x72,
    gruntildas_lair_gobis_valley_puzzle = 0x74,
    gruntildas_lair_mad_monster_mansion_entrance = 0x75,
    gruntildas_lair_640_note_door = 0x76,
    gruntildas_lair_rusty_bucket_bay_entrance = 0x77,
    gruntildas_lair_mad_monster_mansion_rusty_bucket_bay_puzzle = 0x78,
    gruntildas_lair_click_clock_wood_entrance = 0x79,
    gruntildas_lair_mad_monster_mansion_crypt = 0x7A,
    cutscene_lair_hallway_then_open_door = 0x7B,
    cutscene_banjo_sleeping = 0x7C,
    cutscene_tooty_running_to_bottles = 0x7D,
    freezeezy_peak_wozzas_cave = 0x7F,
    gruntildas_lair_path_to_quiz_show = 0x80,
    cutscene_grunty_running_out_door = 0x81,
    cutscene_enter_gruntildas_lair_cutscene = 0x82,
    cutscene_game_over = 0x83,
    cutscene_outside_tower_thunder = 0x85,
    cutscene_gruntilda_rides_outside_her_lair = 0x86,
    cutscene_gruntilda_falling_towards_ground = 0x87,
    cutscene_gruntilda_hits_ground = 0x88,
    cutscene_tootys_being_captured = 0x89,
    rusty_bucket_bay_anchor_room = 0x8B,
    spiral_mountain_banjos_house = 0x8C,
    mad_monster_mansion_inside_loggo = 0x8D,
    gruntildas_lair_furnace_fun = 0x8E,
    treasure_trove_cove_sharkfood_island = 0x8F,
    final_battle_arena = 0x90,
    cutscene_game_select = 0x91,
    gobis_valley_stop_n_swap_egg = 0x92,
    gruntildas_lair_final_battle_puzzle = 0x93,
    cutscene_mumbos_barbaque = 0x94,
    cutscene_beach_ending_have_100_jiggies = 0x95,
    cutscene_beach_about_to_show_cast_list = 0x96,
    cutscene_beach_after_pictures = 0x97,
    cutscene_klungo_cant_move_boulder_without_100_jiggies = 0x98,
    cutscene_klungo_cant_move_boulder_with_100_jiggies = 0x99,

# if __name__ == '__main__':
#     for item in MAP_ENUMS:
#         print(f"{item.name} = 0x{(str(hex(item - 0x071C))[2:]).upper()},")