##################
##### IMPORT #####
##################

from randomizer.constants.int_values.map_enums import MAP_ENUMS
from randomizer.constants.str_values.string_constants import STRING_CONSTANTS

###########################
##### WARP ENTRY DICT #####
###########################

WARP_ENTRY_DICT:dict = {
    STRING_CONSTANTS.spiral_mountain_main_from_banjos_house: (
        MAP_ENUMS.spiral_mountain_main, 0x12,
        (0x986FA,)),
    STRING_CONSTANTS.spiral_mountain_main_from_gruntildas_lair: (
        MAP_ENUMS.spiral_mountain_main, 0x13,
        (0x98742,)),
    STRING_CONSTANTS.mumbos_mountain_main_from_mumbos_hut: (
        MAP_ENUMS.mumbos_mountain_main, 0x01),
    STRING_CONSTANTS.mumbos_mountain_main_from_tickers_tower_lower: (
        MAP_ENUMS.mumbos_mountain_main, 0x02),
    STRING_CONSTANTS.mumbos_mountain_main_from_tickers_tower_upper: (
        MAP_ENUMS.mumbos_mountain_main, 0x03),
    STRING_CONSTANTS.mumbos_mountain_witch_switch_cutscene: (
        MAP_ENUMS.mumbos_mountain_main, 0x04),
    STRING_CONSTANTS.mumbos_mountain_main_from_gruntildas_lair: (
        MAP_ENUMS.mumbos_mountain_main, 0x05),
    STRING_CONSTANTS.treasure_trove_cove_blubbers_ship_top_from_main: (
        MAP_ENUMS.treasure_trove_cove_blubbers_ship, 0x05),
    STRING_CONSTANTS.treasure_trove_cove_blubbers_ship_bottom_from_main: (
        MAP_ENUMS.treasure_trove_cove_blubbers_ship, 0x06),
    STRING_CONSTANTS.treasure_trove_cove_nippers_shell_from_main: (
        MAP_ENUMS.treasure_trove_cove_nippers_shell, 0x01),
    STRING_CONSTANTS.treasure_trove_cove_main_from_sandcastle: (
        MAP_ENUMS.treasure_trove_cove_main, 0x03),
    STRING_CONSTANTS.treasure_trove_cove_main_from_gruntildas_lair: (
        MAP_ENUMS.treasure_trove_cove_main, 0x04),
    STRING_CONSTANTS.treasure_trove_cove_main_from_blubbers_ship_top: (
        MAP_ENUMS.treasure_trove_cove_main, 0x06),
    STRING_CONSTANTS.treasure_trove_cove_main_from_blubbers_ship_bottom: (
        MAP_ENUMS.treasure_trove_cove_main, 0x07),
    STRING_CONSTANTS.treasure_trove_cove_main_from_lighthouse_top: (
        MAP_ENUMS.treasure_trove_cove_main, 0x08),
    STRING_CONSTANTS.treasure_trove_cove_main_from_nippers_shell: (
        MAP_ENUMS.treasure_trove_cove_main, 0x0A),
    STRING_CONSTANTS.treasure_trove_cove_main_from_lighthouse_bottom: (
        MAP_ENUMS.treasure_trove_cove_main, 0x0C),
    STRING_CONSTANTS.treasure_trove_cove_main_from_stair_alcove_top: (
        MAP_ENUMS.treasure_trove_cove_main, 0x0E),
    STRING_CONSTANTS.treasure_trove_cove_main_from_stair_alcove_bottom: (
        MAP_ENUMS.treasure_trove_cove_main, 0x0F),
    STRING_CONSTANTS.treasure_trove_cove_main_from_sharkfood_island: (
        MAP_ENUMS.treasure_trove_cove_main, 0x80),
    STRING_CONSTANTS.treasure_trove_cove_sandcastle_from_main: (
        MAP_ENUMS.treasure_trove_cove_sandcastle, 0x01),
    STRING_CONSTANTS.clankers_cavern_main_from_left_tooth: (
        MAP_ENUMS.clankers_cavern_main, 0x01),
    STRING_CONSTANTS.clankers_cavern_main_from_right_tooth: (
        MAP_ENUMS.clankers_cavern_main, 0x02),
    STRING_CONSTANTS.clankers_cavern_main_from_left_gill: (
        MAP_ENUMS.clankers_cavern_main, 0x03),
    STRING_CONSTANTS.clankers_cavern_main_from_right_gill: (
        MAP_ENUMS.clankers_cavern_main, 0x04),
    STRING_CONSTANTS.clankers_cavern_main_from_gruntildas_lair: (
        MAP_ENUMS.clankers_cavern_main, 0x05),
    STRING_CONSTANTS.mumbos_mountain_tickers_tower_upper_from_main: (
        MAP_ENUMS.mumbos_mountain_tickers_tower, 0x01),
    STRING_CONSTANTS.mumbos_mountain_tickers_tower_lower_from_main: (
        MAP_ENUMS.mumbos_mountain_tickers_tower, 0x02),
    STRING_CONSTANTS.bubblegloop_swamp_main_from_gruntildas_lair: (
        MAP_ENUMS.bubblegloop_swamp_main, 0x02),
    STRING_CONSTANTS.bubblegloop_swamp_main_from_tanktup: (
        MAP_ENUMS.bubblegloop_swamp_main, 0x03),
    STRING_CONSTANTS.bubblegloop_swamp_main_from_vile_right_nostril: (
        MAP_ENUMS.bubblegloop_swamp_main, 0x04),
    STRING_CONSTANTS.bubblegloop_swamp_main_from_vile_left_nostril: (
        MAP_ENUMS.bubblegloop_swamp_main, 0x05),
    STRING_CONSTANTS.bubblegloop_swamp_main_from_mumbos_hut: (
        MAP_ENUMS.bubblegloop_swamp_main, 0x06),
    STRING_CONSTANTS.mumbos_mountain_mumbos_hut_from_main: (
        MAP_ENUMS.mumbos_mountain_mumbos_hut, 0x01),
    STRING_CONSTANTS.bubblegloop_swamp_vile_right_nostril_from_main: (
        MAP_ENUMS.bubblegloop_swamp_mr_vile, 0x03),
    STRING_CONSTANTS.bubblegloop_swamp_vile_left_nostril_from_main: (
        MAP_ENUMS.bubblegloop_swamp_mr_vile, 0x04),
    STRING_CONSTANTS.bubblegloop_swamp_tanktup_from_main: (
        MAP_ENUMS.bubblegloop_swamp_tip_tup_chior, 0x01),
    STRING_CONSTANTS.gobis_valley_main_from_jinxy: (
        MAP_ENUMS.gobis_valley_main, 0x02),
    STRING_CONSTANTS.gobis_valley_main_from_matching_puzzle: (
        MAP_ENUMS.gobis_valley_main, 0x03),
    STRING_CONSTANTS.gobis_valley_main_from_king_sandybutt_front: (
        MAP_ENUMS.gobis_valley_main, 0x04),
    STRING_CONSTANTS.gobis_valley_main_from_water_pyramid_lower: (
        MAP_ENUMS.gobis_valley_main, 0x05),
    STRING_CONSTANTS.gobis_valley_main_from_rubee: (
        MAP_ENUMS.gobis_valley_main, 0x06),
    STRING_CONSTANTS.gobis_valley_main_from_king_sandybutt_back: (
        MAP_ENUMS.gobis_valley_main, 0x07),
    STRING_CONSTANTS.gobis_valley_main_from_gruntildas_lair: (
        MAP_ENUMS.gobis_valley_main, 0x08),
    STRING_CONSTANTS.gobis_valley_main_from_stop_n_swap_chamber: (
        MAP_ENUMS.gobis_valley_main, 0x0A),
    STRING_CONSTANTS.gobis_valley_matching_puzzle_from_main: (
        MAP_ENUMS.gobis_valley_matching_puzzle, 0x01),
    STRING_CONSTANTS.gobis_valley_king_sandybutt_from_main: (
        MAP_ENUMS.gobis_valley_king_sandybutts_tomb, 0x01),
    STRING_CONSTANTS.gobis_valley_water_pyramid_cutscene: (
        MAP_ENUMS.gobis_valley_water_pyramid, 0x01),
    STRING_CONSTANTS.gobis_valley_water_pyramid_from_upper: (
        MAP_ENUMS.gobis_valley_water_pyramid, 0x02),
    STRING_CONSTANTS.gobis_valley_water_pyramid_from_lower: (
        MAP_ENUMS.gobis_valley_water_pyramid, 0x06),
    STRING_CONSTANTS.gobis_valley_rubee_from_main: (
        MAP_ENUMS.gobis_valley_rupee, 0x07),
    STRING_CONSTANTS.gobis_valley_jinxy_from_main: (
        MAP_ENUMS.gobis_valley_jinxy, 0x02),
    STRING_CONSTANTS.mad_monster_mansion_main_from_dining_room: (
        MAP_ENUMS.mad_monster_mansion_main, 0x01),
    STRING_CONSTANTS.mad_monster_mansion_main_from_well_top: (
        MAP_ENUMS.mad_monster_mansion_main, 0x03),
    STRING_CONSTANTS.mad_monster_mansion_main_from_tumblar: (
        MAP_ENUMS.mad_monster_mansion_main, 0x04),
    STRING_CONSTANTS.mad_monster_mansion_main_from_church_door: (
        MAP_ENUMS.mad_monster_mansion_main, 0x05),
    STRING_CONSTANTS.mad_monster_mansion_main_from_church_window: (
        MAP_ENUMS.mad_monster_mansion_main, 0x06),
    STRING_CONSTANTS.mad_monster_mansion_main_from_rain_barrel: (
        MAP_ENUMS.mad_monster_mansion_main, 0x08),
    STRING_CONSTANTS.mad_monster_mansion_main_from_cellar: (
        MAP_ENUMS.mad_monster_mansion_main, 0x09),
    STRING_CONSTANTS.mad_monster_mansion_main_from_red_feather_room: (
        MAP_ENUMS.mad_monster_mansion_main, 0x0A),
    STRING_CONSTANTS.mad_monster_mansion_main_from_blue_egg_room: (
        MAP_ENUMS.mad_monster_mansion_main, 0x0B),
    STRING_CONSTANTS.mad_monster_mansion_main_from_bathroom: (
        MAP_ENUMS.mad_monster_mansion_main, 0x0C),
    STRING_CONSTANTS.mad_monster_mansion_main_from_empty_honeycomb_room: (
        MAP_ENUMS.mad_monster_mansion_main, 0x0D),
    STRING_CONSTANTS.mad_monster_mansion_main_from_bedroom: (
        MAP_ENUMS.mad_monster_mansion_main, 0x0E),
    STRING_CONSTANTS.mad_monster_mansion_main_from_note_room: (
        MAP_ENUMS.mad_monster_mansion_main, 0x0F),
    STRING_CONSTANTS.mad_monster_mansion_main_from_church_tower_upper: (
        MAP_ENUMS.mad_monster_mansion_main, 0x10),
    STRING_CONSTANTS.mad_monster_mansion_main_from_church_tower_lower: (
        MAP_ENUMS.mad_monster_mansion_main, 0x11),
    STRING_CONSTANTS.mad_monster_mansion_main_from_mumbos_hut: (
        MAP_ENUMS.mad_monster_mansion_main, 0x12),
    STRING_CONSTANTS.mad_monster_mansion_main_from_well_bottom: (
        MAP_ENUMS.mad_monster_mansion_main, 0x13),
    STRING_CONSTANTS.mad_monster_mansion_main_from_level_entrance: (
        MAP_ENUMS.mad_monster_mansion_main, 0x14),
    STRING_CONSTANTS.mad_monster_mansion_church_nave_from_main: (
        MAP_ENUMS.mad_monster_mansion_church_main, 0x01),
    STRING_CONSTANTS.mad_monster_mansion_cellar_from_main: (
        MAP_ENUMS.mad_monster_mansion_cellar, 0x01),
    STRING_CONSTANTS.clankers_cavern_blowhole_from_main: (
        MAP_ENUMS.clankers_cavern_blowhole, 0x01),
    STRING_CONSTANTS.clankers_cavern_mouth_belly_from_blowhole_belly: (
        MAP_ENUMS.clankers_cavern_mouth_belly, 0x01),
    STRING_CONSTANTS.clankers_cavern_mouth_belly_from_blowhole_mouth: (
        MAP_ENUMS.clankers_cavern_mouth_belly, 0x02),
    STRING_CONSTANTS.clankers_cavern_mouth_belly_from_wonderwing_room: (
        MAP_ENUMS.clankers_cavern_mouth_belly, 0x03),
    STRING_CONSTANTS.clankers_cavern_mouth_belly_from_right_gill: (
        MAP_ENUMS.clankers_cavern_mouth_belly, 0x04),
    STRING_CONSTANTS.clankers_cavern_mouth_belly_from_left_gill: (
        MAP_ENUMS.clankers_cavern_mouth_belly, 0x05),
    STRING_CONSTANTS.clankers_cavern_mouth_belly_from_right_tooth: (
        MAP_ENUMS.clankers_cavern_mouth_belly, 0x06),
    STRING_CONSTANTS.clankers_cavern_mouth_belly_from_left_tooth: (
        MAP_ENUMS.clankers_cavern_mouth_belly, 0x07),
    STRING_CONSTANTS.clankers_cavern_wonderwing_from_mouth_belly: (
        MAP_ENUMS.clankers_cavern_wonderwing, 0x01),
    STRING_CONSTANTS.mad_monster_mansion_tumblar_from_main: (
        MAP_ENUMS.mad_monster_mansion_tumblar, 0x01),
    STRING_CONSTANTS.mad_monster_mansion_well_top_from_main: (
        MAP_ENUMS.mad_monster_mansion_well, 0x01),
    STRING_CONSTANTS.mad_monster_mansion_well_bottom_from_main: (
        MAP_ENUMS.mad_monster_mansion_well, 0x02),
    STRING_CONSTANTS.mad_monster_mansion_dining_room_from_door: (
        MAP_ENUMS.mad_monster_mansion_dining_room, 0x01),
    STRING_CONSTANTS.mad_monster_mansion_dining_room_from_chimney: (
        MAP_ENUMS.mad_monster_mansion_dining_room, 0x02),
    STRING_CONSTANTS.freezeezy_peak_main_from_gruntildas_lair: (
        MAP_ENUMS.freezeezy_peak_main, 0x01),
    STRING_CONSTANTS.freezeezy_peak_main_from_wozzas_cave: (
        MAP_ENUMS.freezeezy_peak_main, 0x06),
    STRING_CONSTANTS.freezeezy_peak_main_from_mumbos_hut: (
        MAP_ENUMS.freezeezy_peak_main, 0x07),
    STRING_CONSTANTS.freezeezy_peak_main_from_igloo: (
        MAP_ENUMS.freezeezy_peak_main, 0x08),
    STRING_CONSTANTS.freezeezy_peak_main_from_christmas_tree: (
        MAP_ENUMS.freezeezy_peak_main, 0x09),
    STRING_CONSTANTS.mad_monster_mansion_blue_egg_room_from_main: (
        MAP_ENUMS.mad_monster_mansion_egg_room, 0x01),
    STRING_CONSTANTS.mad_monster_mansion_note_room_from_main: (
        MAP_ENUMS.mad_monster_mansion_note_room, 0x01),
    STRING_CONSTANTS.mad_monster_mansion_red_feather_room_from_main: (
        MAP_ENUMS.mad_monster_mansion_red_feather_room, 0x01),
    STRING_CONSTANTS.mad_monster_mansion_church_window_from_main: (
        MAP_ENUMS.mad_monster_mansion_secret_church_room, 0x01),
    STRING_CONSTANTS.mad_monster_mansion_bathroom_from_main: (
        MAP_ENUMS.mad_monster_mansion_bathroom, 0x01),
    STRING_CONSTANTS.mad_monster_mansion_bathroom_from_loggo: (
        MAP_ENUMS.mad_monster_mansion_bathroom, 0x04),
    STRING_CONSTANTS.mad_monster_mansion_bedroom_from_main: (
        MAP_ENUMS.mad_monster_mansion_bedroom, 0x01),
    STRING_CONSTANTS.mad_monster_mansion_empty_honeycomb_room_from_main: (
        MAP_ENUMS.mad_monster_mansion_honeycomb_room, 0x01),
    STRING_CONSTANTS.mad_monster_mansion_rain_barrel_top_from_main: (
        MAP_ENUMS.mad_monster_mansion_drainpipe, 0x01),
    STRING_CONSTANTS.mad_monster_mansion_rain_barrel_bottom_from_main: (
        MAP_ENUMS.mad_monster_mansion_drainpipe, 0x02),
    STRING_CONSTANTS.mad_monster_mansion_mumbos_hut_from_main: (
        MAP_ENUMS.mad_monster_mansion_mumbos_hut, 0x01),
    STRING_CONSTANTS.rusty_bucket_bay_main_from_captains_room_window: (
        MAP_ENUMS.rusty_bucket_bay_captains_window, 0x01),
    STRING_CONSTANTS.rusty_bucket_bay_main_from_cabin_room_window: (
        MAP_ENUMS.rusty_bucket_bay_captains_window, 0x02),
    STRING_CONSTANTS.rusty_bucket_bay_main_from_engine_room_pipe: (
        MAP_ENUMS.rusty_bucket_bay_captains_window, 0x03),
    STRING_CONSTANTS.rusty_bucket_bay_main_from_kitchen_pipe: (
        MAP_ENUMS.rusty_bucket_bay_captains_window, 0x04),
    STRING_CONSTANTS.rusty_bucket_bay_main_from_navigation_room_window: (
        MAP_ENUMS.rusty_bucket_bay_captains_window, 0x05),
    STRING_CONSTANTS.rusty_bucket_bay_main_from_boom_box_pipe: (
        MAP_ENUMS.rusty_bucket_bay_captains_window, 0x06),
    STRING_CONSTANTS.rusty_bucket_bay_main_from_engine_room_door: (
        MAP_ENUMS.rusty_bucket_bay_captains_window, 0x07),
    STRING_CONSTANTS.rusty_bucket_bay_main_from_boat_room: (
        MAP_ENUMS.rusty_bucket_bay_captains_window, 0x08),
    STRING_CONSTANTS.rusty_bucket_bay_main_from_chompa_container: (
        MAP_ENUMS.rusty_bucket_bay_captains_window, 0x09),
    STRING_CONSTANTS.rusty_bucket_bay_main_from_seaman_grublin_container: (
        MAP_ENUMS.rusty_bucket_bay_captains_window, 0x0A),
    STRING_CONSTANTS.rusty_bucket_bay_main_from_mini_boom_box_container: (
        MAP_ENUMS.rusty_bucket_bay_captains_window, 0x0B),
    STRING_CONSTANTS.rusty_bucket_bay_main_from_boss_boom_box_room: (
        MAP_ENUMS.rusty_bucket_bay_captains_window, 0x0C),
    STRING_CONSTANTS.rusty_bucket_bay_main_from_chump_warehouse: (
        MAP_ENUMS.rusty_bucket_bay_captains_window, 0x0D),
    STRING_CONSTANTS.rusty_bucket_bay_main_from_gruntildas_lair: (
        MAP_ENUMS.rusty_bucket_bay_captains_window, 0x10),
    STRING_CONSTANTS.rusty_bucket_bay_main_from_anchor_room: (
        MAP_ENUMS.rusty_bucket_bay_captains_window, 0x13),
    STRING_CONSTANTS.rusty_bucket_bay_engine_room_from_door: (
        MAP_ENUMS.rusty_bucket_bay_engine_room, 0x01),
    STRING_CONSTANTS.rusty_bucket_bay_engine_room_from_pipe: (
        MAP_ENUMS.rusty_bucket_bay_engine_room, 0x04),
    STRING_CONSTANTS.rusty_bucket_bay_chump_warehouse_from_door: (
        MAP_ENUMS.rusty_bucket_bay_chump_warehouse, 0x01),
    STRING_CONSTANTS.rusty_bucket_bay_chump_warehouse_from_window: (
        MAP_ENUMS.rusty_bucket_bay_chump_warehouse, 0x02),
    STRING_CONSTANTS.rusty_bucket_bay_boat_room_from_main: (
        MAP_ENUMS.rusty_bucket_bay_boat_room, 0x01),
    STRING_CONSTANTS.rusty_bucket_bay_chompa_container_from_main: (
        MAP_ENUMS.rusty_bucket_bay_chompa_container, 0x01),
    STRING_CONSTANTS.rusty_bucket_bay_boom_box_container_from_main: (
        MAP_ENUMS.rusty_bucket_bay_boom_box_container, 0x01),
    STRING_CONSTANTS.rusty_bucket_bay_kitchen_pipe_from_main: (
        MAP_ENUMS.rusty_bucket_bay_kitchen_pipe, 0x01),
    STRING_CONSTANTS.rusty_bucket_bay_navigation_room_window_from_main: (
        MAP_ENUMS.rusty_bucket_bay_navigation_window, 0x01),
    STRING_CONSTANTS.rusty_bucket_bay_seaman_grublin_container_from_main: (
        MAP_ENUMS.rusty_bucket_bay_seaman_grublins_container, 0x01),
    STRING_CONSTANTS.rusty_bucket_bay_captains_room_window_from_main: (
        MAP_ENUMS.rusty_bucket_bay_captains_window, 0x01),
    STRING_CONSTANTS.click_clock_wood_hub_from_winter_main: (
        MAP_ENUMS.click_clock_wood_main_hub, 0x01),
    STRING_CONSTANTS.click_clock_wood_hub_from_spring_main: (
        MAP_ENUMS.click_clock_wood_main_hub, 0x02),
    STRING_CONSTANTS.click_clock_wood_hub_from_summer_main: (
        MAP_ENUMS.click_clock_wood_main_hub, 0x03),
    STRING_CONSTANTS.click_clock_wood_hub_from_autumn_main: (
        MAP_ENUMS.click_clock_wood_main_hub, 0x04),
    STRING_CONSTANTS.click_clock_wood_hub_from_gruntildas_lair: (
        MAP_ENUMS.click_clock_wood_main_hub, 0x05),
    STRING_CONSTANTS.freezeezy_peak_igloo_from_main: (
        MAP_ENUMS.freezeezy_peak_igloo, 0x01),
    STRING_CONSTANTS.click_clock_wood_spring_main_from_hub: (
        MAP_ENUMS.click_clock_wood_spring_main, 0x01),
    STRING_CONSTANTS.click_clock_wood_spring_main_from_spring_nabnut_window: (
        MAP_ENUMS.click_clock_wood_spring_main, 0x04),
    STRING_CONSTANTS.click_clock_wood_spring_main_from_spring_zubbas: (
        MAP_ENUMS.click_clock_wood_spring_main, 0x06),
    STRING_CONSTANTS.click_clock_wood_spring_main_from_spring_nabnut_door: (
        MAP_ENUMS.click_clock_wood_spring_main, 0x07),
    STRING_CONSTANTS.click_clock_wood_spring_main_from_spring_whipcrack_room: (
        MAP_ENUMS.click_clock_wood_spring_main, 0x08),
    STRING_CONSTANTS.click_clock_wood_spring_main_from_spring_mumbos_hut: (
        MAP_ENUMS.click_clock_wood_spring_main, 0x09),
    STRING_CONSTANTS.click_clock_wood_summer_main_from_hub: (
        MAP_ENUMS.click_clock_wood_summer_main, 0x01),
    STRING_CONSTANTS.click_clock_wood_summer_main_from_summer_nabnut_window: (
        MAP_ENUMS.click_clock_wood_summer_main, 0x04),
    STRING_CONSTANTS.click_clock_wood_summer_main_from_summer_zubbas: (
        MAP_ENUMS.click_clock_wood_summer_main, 0x06),
    STRING_CONSTANTS.click_clock_wood_summer_main_from_summer_nabnut_door: (
        MAP_ENUMS.click_clock_wood_summer_main, 0x07),
    STRING_CONSTANTS.click_clock_wood_summer_main_from_summer_whipcrack_room: (
        MAP_ENUMS.click_clock_wood_summer_main, 0x08),
    STRING_CONSTANTS.click_clock_wood_summer_main_from_summer_mumbos_hut: (
        MAP_ENUMS.click_clock_wood_summer_main, 0x09),
    STRING_CONSTANTS.click_clock_wood_autumn_main_from_hub: (
        MAP_ENUMS.click_clock_wood_autumn_main, 0x01),
    STRING_CONSTANTS.click_clock_wood_autumn_main_from_autumn_nabnut_window: (
        MAP_ENUMS.click_clock_wood_autumn_main, 0x04),
    STRING_CONSTANTS.click_clock_wood_autumn_main_from_autumn_zubbas: (
        MAP_ENUMS.click_clock_wood_autumn_main, 0x05),
    STRING_CONSTANTS.click_clock_wood_autumn_main_from_autumn_flooded_attic: (
        MAP_ENUMS.click_clock_wood_autumn_main, 0x06),
    STRING_CONSTANTS.click_clock_wood_autumn_main_from_autumn_nabnut_door: (
        MAP_ENUMS.click_clock_wood_autumn_main, 0x07),
    STRING_CONSTANTS.click_clock_wood_autumn_main_from_autumn_whipcrack_room: (
        MAP_ENUMS.click_clock_wood_autumn_main, 0x08),
    STRING_CONSTANTS.click_clock_wood_autumn_main_from_autumn_mumbos_hut: (
        MAP_ENUMS.click_clock_wood_autumn_main, 0x09),
    STRING_CONSTANTS.click_clock_wood_winter_main_from_hub: (
        MAP_ENUMS.click_clock_wood_winter_main, 0x01),
    STRING_CONSTANTS.click_clock_wood_winter_main_from_winter_nabnut_window: (
        MAP_ENUMS.click_clock_wood_winter_main, 0x04),
    STRING_CONSTANTS.click_clock_wood_winter_main_from_winter_flooded_attic: (
        MAP_ENUMS.click_clock_wood_winter_main, 0x05),
    STRING_CONSTANTS.click_clock_wood_winter_main_from_winter_acorn_storage: (
        MAP_ENUMS.click_clock_wood_winter_main, 0x06),
    STRING_CONSTANTS.click_clock_wood_winter_main_from_winter_whipcrack_room: (
        MAP_ENUMS.click_clock_wood_winter_main, 0x08),
    STRING_CONSTANTS.click_clock_wood_winter_main_from_winter_mumbos_hut: (
        MAP_ENUMS.click_clock_wood_winter_main, 0x09),
    STRING_CONSTANTS.bubblegloop_swamp_mumbos_hut_from_main: (
        MAP_ENUMS.bubblegloop_swamp_mumbos_hut, 0x01),
    STRING_CONSTANTS.freezeezy_peak_mumbos_hut_from_main: (
        MAP_ENUMS.freezeezy_peak_mumbos_hut, 0x01),
    STRING_CONSTANTS.click_clock_wood_spring_mumbos_hut_from_spring_main: (
        MAP_ENUMS.click_clock_wood_spring_mumbos_hut, 0x01),
    STRING_CONSTANTS.click_clock_wood_summer_mumbos_hut_from_summer_main: (
        MAP_ENUMS.click_clock_wood_summer_mumbos_hut, 0x01),
    STRING_CONSTANTS.click_clock_wood_autumn_mumbos_hut_from_autumn_main: (
        MAP_ENUMS.click_clock_wood_autumn_mumbos_hut, 0x01),
    STRING_CONSTANTS.click_clock_wood_winter_mumbos_hut_from_winter_main: (
        MAP_ENUMS.click_clock_wood_winter_mumbos_hut),
    STRING_CONSTANTS.freezeezy_peak_christmas_tree_from_main: (
        MAP_ENUMS.freezeezy_peak_christmas_tree, 0x01),
    STRING_CONSTANTS.click_clock_wood_spring_zubbas_from_spring_main: (
        MAP_ENUMS.click_clock_wood_spring_zubbas, 0x02),
    STRING_CONSTANTS.click_clock_wood_summer_zubbas_hut_from_summer_main: (
        MAP_ENUMS.click_clock_wood_summer_zubbas, 0x01),
    STRING_CONSTANTS.click_clock_wood_autumn_zubbas_hut_from_autumn_main: (
        MAP_ENUMS.click_clock_wood_autumn_zubbas, 0x02),
    STRING_CONSTANTS.click_clock_wood_spring_nabnut_door_from_spring_main: (
        MAP_ENUMS.click_clock_wood_spring_nabnuts, 0x01),
    STRING_CONSTANTS.click_clock_wood_spring_nabnut_window_from_spring_main: (
        MAP_ENUMS.click_clock_wood_spring_nabnuts, 0x02),
    STRING_CONSTANTS.click_clock_wood_summer_nabnut_door_from_summer_main: (
        MAP_ENUMS.click_clock_wood_summer_nabnuts, 0x01),
    STRING_CONSTANTS.click_clock_wood_summer_nabnut_window_from_summer_main: (
        MAP_ENUMS.click_clock_wood_summer_nabnuts, 0x02),
    STRING_CONSTANTS.click_clock_wood_autumn_nabnut_door_from_autumn_main: (
        MAP_ENUMS.click_clock_wood_autumn_nabnuts, 0x01),
    STRING_CONSTANTS.click_clock_wood_autumn_nabnut_window_from_autumn_main: (
        MAP_ENUMS.click_clock_wood_autumn_nabnuts, 0x02),
    STRING_CONSTANTS.click_clock_wood_winter_nabnut_window_from_winter_main: (
        MAP_ENUMS.click_clock_wood_winter_nabnuts, 0x02),
    STRING_CONSTANTS.click_clock_wood_winter_acorn_storage_from_winter_main: (
        MAP_ENUMS.click_clock_wood_winter_acorn_attic, 0x01),
    STRING_CONSTANTS.click_clock_wood_autumn_flooded_attic_from_autumn_main: (
        MAP_ENUMS.click_clock_wood_autumn_flooded_attic, 0x01),
    STRING_CONSTANTS.click_clock_wood_winter_flooded_attic_from_winter_main: (
        MAP_ENUMS.click_clock_wood_winter_flooded_attic, 0x01),
    STRING_CONSTANTS.click_clock_wood_spring_whipcrack_room_from_spring_main: (
        MAP_ENUMS.click_clock_wood_spring_whipcracks, 0x01),
    STRING_CONSTANTS.click_clock_wood_summer_whipcrack_room_from_summer_main: (
        MAP_ENUMS.click_clock_wood_summer_whipcracks, 0x01),
    STRING_CONSTANTS.click_clock_wood_autumn_whipcrack_room_from_autumn_main: (
        MAP_ENUMS.click_clock_wood_autumn_whipcracks, 0x01),
    STRING_CONSTANTS.click_clock_wood_winter_whipcrack_room_from_winter_main: (
        MAP_ENUMS.click_clock_wood_winter_whipcracks, 0x01),
    STRING_CONSTANTS.gruntildas_lair_mm_lobby_from_ttc_cc_puzzles: (
        MAP_ENUMS.gruntildas_lair_mumbos_mountain_entrance, 0x01),
    STRING_CONSTANTS.gruntildas_lair_mm_lobby_from_mumbos_mountain_main: (
        MAP_ENUMS.gruntildas_lair_mumbos_mountain_entrance, 0x02),
    STRING_CONSTANTS.gruntildas_lair_mm_lobby_from_spiral_mountain_main: (
        MAP_ENUMS.gruntildas_lair_mumbos_mountain_entrance, 0x12,
        (0x9871E, 0x98BAE,)),
    STRING_CONSTANTS.gruntildas_lair_ttc_cc_puzzles_from_mumbos_mountain_lobby: (
        MAP_ENUMS.gruntildas_lair_treasure_trove_cove_clankers_cavern_puzzles, 0x01),
    # gruntildas_lair_ttc_cc_puzzles_from_ccw_puzzle?
    STRING_CONSTANTS.gruntildas_lair_ccw_puzzle_from_ttc_cc_puzzles: (
        MAP_ENUMS.gruntildas_lair_click_clock_wood_puzzle, 0x01),
    STRING_CONSTANTS.gruntildas_lair_ccw_puzzle_from_pipe_room: (
        MAP_ENUMS.gruntildas_lair_click_clock_wood_puzzle, 0x02),
    STRING_CONSTANTS.gruntildas_lair_ccw_puzzle_from_ttc_lobby: (
        MAP_ENUMS.gruntildas_lair_click_clock_wood_puzzle, 0x03),
    STRING_CONSTANTS.gruntildas_lair_ccw_puzzle_from_cc_lobby: (
        MAP_ENUMS.gruntildas_lair_click_clock_wood_puzzle, 0x04),
    STRING_CONSTANTS.gruntildas_lair_ccw_puzzle_from_grunty_statue: (
        MAP_ENUMS.gruntildas_lair_click_clock_wood_puzzle, 0x05),
    STRING_CONSTANTS.gruntildas_lair_pipe_room_from_ccw_puzzle: (
        MAP_ENUMS.gruntildas_lair_cauldron_pipe_room, 0x01),
    STRING_CONSTANTS.gruntildas_lair_ttc_lobby_from_ccw_puzzle: (
        MAP_ENUMS.gruntildas_lair_treasure_trove_cove_entrance, 0x01),
    STRING_CONSTANTS.gruntildas_lair_ttc_lobby_from_treasure_trove_cove_main: (
        MAP_ENUMS.gruntildas_lair_treasure_trove_cove_entrance, 0x04),
    STRING_CONSTANTS.gruntildas_lair_gv_lobby_from_grunty_statue: (
        MAP_ENUMS.gruntildas_lair_gobis_valley_entrance, 0x01),
    STRING_CONSTANTS.gruntildas_lair_gv_lobby_from_fp_lobby: (
        MAP_ENUMS.gruntildas_lair_gobis_valley_entrance, 0x02),
    STRING_CONSTANTS.gruntildas_lair_gv_lobby_from_gobis_valley_main: (
        MAP_ENUMS.gruntildas_lair_gobis_valley_entrance, 0x03),
    STRING_CONSTANTS.gruntildas_lair_fp_lobby_from_gv_lobby: (
        MAP_ENUMS.gruntildas_lair_freezeezy_peak_entrance, 0x01),
    STRING_CONSTANTS.gruntildas_lair_fp_lobby_from_640_note_door: (
        MAP_ENUMS.gruntildas_lair_freezeezy_peak_entrance, 0x02),
    STRING_CONSTANTS.gruntildas_lair_fp_lobby_from_gv_puzzle: (
        MAP_ENUMS.gruntildas_lair_freezeezy_peak_entrance, 0x03),
    STRING_CONSTANTS.gruntildas_lair_fp_lobby_from_freezeezy_peak_main: (
        MAP_ENUMS.gruntildas_lair_freezeezy_peak_entrance, 0x04),
    STRING_CONSTANTS.gruntildas_lair_cc_lobby_from_ccw_puzzle: (
        MAP_ENUMS.gruntildas_lair_clankers_cavern_entrance, 0x01),
    STRING_CONSTANTS.gruntildas_lair_cc_lobby_from_clankers_cavern_main: (
        MAP_ENUMS.gruntildas_lair_clankers_cavern_entrance, 0x02),
    STRING_CONSTANTS.gruntildas_lair_grunty_statue_from_gv_lobby_note_door: (
        MAP_ENUMS.gruntildas_lair_pointing_grunty_statue, 0x01),
    STRING_CONSTANTS.gruntildas_lair_grunty_statue_from_ccw_puzzle: (
        MAP_ENUMS.gruntildas_lair_pointing_grunty_statue, 0x02),
    STRING_CONSTANTS.gruntildas_lair_grunty_statue_from_bgs_lobby: (
        MAP_ENUMS.gruntildas_lair_pointing_grunty_statue, 0x03),
    STRING_CONSTANTS.gruntildas_lair_grunty_statue_from_gv_lobby_witch_switch: (
        MAP_ENUMS.gruntildas_lair_pointing_grunty_statue, 0x04),
    STRING_CONSTANTS.gruntildas_lair_bgs_lobby_from_grunty_statue: (
        MAP_ENUMS.gruntildas_lair_bubblegloop_swamp_entrance, 0x01),
    STRING_CONSTANTS.gruntildas_lair_bgs_lobby_from_bubblegloop_swamp_main: (
        MAP_ENUMS.gruntildas_lair_bubblegloop_swamp_entrance, 0x02),
    STRING_CONSTANTS.gruntildas_lair_gv_puzzle_from_mmm_lobby: (
        MAP_ENUMS.gruntildas_lair_gobis_valley_puzzle, 0x01),
    STRING_CONSTANTS.gruntildas_lair_gv_puzzle_from_fp_lobby: (
        MAP_ENUMS.gruntildas_lair_gobis_valley_puzzle, 0x02),
    STRING_CONSTANTS.gruntildas_lair_mmm_lobby_from_gv_puzzle: (
        MAP_ENUMS.gruntildas_lair_mad_monster_mansion_entrance, 0x01),
    STRING_CONSTANTS.gruntildas_lair_mmm_lobby_from_mad_monster_mansion_main: (
        MAP_ENUMS.gruntildas_lair_mad_monster_mansion_entrance, 0x02),
    STRING_CONSTANTS.gruntildas_lair_mmm_lobby_from_crypt: (
        MAP_ENUMS.gruntildas_lair_mad_monster_mansion_entrance, 0x03),
    STRING_CONSTANTS.gruntildas_lair_640_note_door_from_fp_lobby: (
        MAP_ENUMS.gruntildas_lair_640_note_door, 0x01),
    STRING_CONSTANTS.gruntildas_lair_640_note_door_from_ccw_lobby_token: (
        MAP_ENUMS.gruntildas_lair_640_note_door, 0x02),
    STRING_CONSTANTS.gruntildas_lair_640_note_door_from_ccw_lobby_note_door: (
        MAP_ENUMS.gruntildas_lair_640_note_door, 0x03),
    STRING_CONSTANTS.gruntildas_lair_640_note_door_from_rbb_lobby: (
        MAP_ENUMS.gruntildas_lair_640_note_door, 0x04),
    STRING_CONSTANTS.gruntildas_lair_rbb_lobby_from_640_note_door: (
        MAP_ENUMS.gruntildas_lair_rusty_bucket_bay_entrance, 0x01),
    STRING_CONSTANTS.gruntildas_lair_rbb_lobby_from_rusty_bucket_bay_main: (
        MAP_ENUMS.gruntildas_lair_rusty_bucket_bay_entrance, 0x02),
    STRING_CONSTANTS.gruntildas_lair_rbb_lobby_from_rbb_puzzle: (
        MAP_ENUMS.gruntildas_lair_rusty_bucket_bay_entrance, 0x03),
    STRING_CONSTANTS.gruntildas_lair_rbb_lobby_from_mmm_puzzle: (
        MAP_ENUMS.gruntildas_lair_rusty_bucket_bay_entrance, 0x04),
    STRING_CONSTANTS.gruntildas_lair_mmm_puzzle_from_rbb_lobby: (
        MAP_ENUMS.gruntildas_lair_mad_monster_mansion_rusty_bucket_bay_puzzle, 0x01),
    STRING_CONSTANTS.gruntildas_lair_rbb_puzzle_from_rbb_lobby: (
        MAP_ENUMS.gruntildas_lair_mad_monster_mansion_rusty_bucket_bay_puzzle, 0x02),
    STRING_CONSTANTS.gruntildas_lair_ccw_lobby_from_640_note_door_note_door: (
        MAP_ENUMS.gruntildas_lair_click_clock_wood_entrance, 0x01),
    STRING_CONSTANTS.gruntildas_lair_ccw_lobby_from_640_note_door_token: (
        MAP_ENUMS.gruntildas_lair_click_clock_wood_entrance, 0x02),
    STRING_CONSTANTS.gruntildas_lair_ccw_lobby_from_path_to_furnace_fun: (
        MAP_ENUMS.gruntildas_lair_click_clock_wood_entrance, 0x03),
    STRING_CONSTANTS.gruntildas_lair_ccw_lobby_from_click_clock_wood_main: (
        MAP_ENUMS.gruntildas_lair_click_clock_wood_entrance, 0x06),
    STRING_CONSTANTS.gruntildas_lair_crypt_from_mmm_lobby: (
        MAP_ENUMS.gruntildas_lair_mad_monster_mansion_crypt, 0x01),
    STRING_CONSTANTS.freezeezy_peak_wozzas_cave_from_main: (
        MAP_ENUMS.freezeezy_peak_wozzas_cave, 0x01),
    STRING_CONSTANTS.gruntildas_lair_path_to_furnace_fun_from_ccw_lobby: (
        MAP_ENUMS.gruntildas_lair_path_to_quiz_show, 0x01),
    STRING_CONSTANTS.gruntildas_lair_path_to_furnace_fun_from_furnace_fun: (
        MAP_ENUMS.gruntildas_lair_path_to_quiz_show, 0x02),
    STRING_CONSTANTS.rusty_bucket_bay_anchor_room_from_main: (
        MAP_ENUMS.rusty_bucket_bay_anchor_room, 0x04),
    STRING_CONSTANTS.spiral_mountain_banjos_house_from_main: (
        MAP_ENUMS.spiral_mountain_banjos_house, 0x01,
        (0x986D6,)),
    STRING_CONSTANTS.mad_monster_mansion_inside_loggo_from_bathroom: (
        MAP_ENUMS.mad_monster_mansion_inside_loggo, 0x04),
    STRING_CONSTANTS.gruntildas_lair_furnace_fun_from_path_to_furnace_fun: (
        MAP_ENUMS.gruntildas_lair_furnace_fun, 0x02),
    STRING_CONSTANTS.gruntildas_lair_furnace_fun_from_dingpot: (
        MAP_ENUMS.gruntildas_lair_furnace_fun, 0x05),
    STRING_CONSTANTS.treasure_trove_cove_sharkfood_island_from_main: (
        MAP_ENUMS.treasure_trove_cove_sharkfood_island, 0x01),
    STRING_CONSTANTS.final_battle_from_gruntildas_lair_dingpot: (
        MAP_ENUMS.final_battle_arena, 0x01),
    STRING_CONSTANTS.gobis_valley_stop_n_swap_from_main: (
        MAP_ENUMS.gobis_valley_stop_n_swap_egg, 0x05),
    STRING_CONSTANTS.gruntildas_lair_dingpot_from_furnace_fun: (
        MAP_ENUMS.gruntildas_lair_final_battle_puzzle, 0x05),
}