from randomizer.contants.enums.ability_enums import ABILITY_ENUMS
from randomizer.contants.variables.gui_variables import \
    BEAK_BARGE_STR, BEAK_BOMB_STR, BEAK_BUSTER_STR, \
    CLAW_SWIPE_STR, CLIMB_STR, EGG_FIRING_STR, \
    FEATHERY_FLAP_STR, FLAP_FLIP_STR, FLIGHT_STR, \
    HIGH_JUMP_STR, RAT_A_TAP_RAP_STR, ROLL_STR, \
    SHOCK_JUMP_STR, STILT_STRIDE_STR, DIVE_STR, \
    TALON_TROT_STR, TURBO_TALON_TROT_STR, \
    WONDERWING_STR, NOTE_DOOR_STR

GUI_MOVE_ENUM_DICT:dict = {
    BEAK_BARGE_STR: ABILITY_ENUMS.beak_barge,
    BEAK_BOMB_STR: ABILITY_ENUMS.beak_bomb,
    BEAK_BUSTER_STR: ABILITY_ENUMS.beak_buster,
    CLAW_SWIPE_STR: ABILITY_ENUMS.claw_swipe,
    CLIMB_STR: ABILITY_ENUMS.climb,
    EGG_FIRING_STR: ABILITY_ENUMS.egg_firing,
    FEATHERY_FLAP_STR: ABILITY_ENUMS.feathery_flap,
    FLAP_FLIP_STR: ABILITY_ENUMS.flap_flip,
    FLIGHT_STR: ABILITY_ENUMS.flight,
    HIGH_JUMP_STR: ABILITY_ENUMS.high_jump,
    RAT_A_TAP_RAP_STR: ABILITY_ENUMS.rat_a_tat_rap,
    ROLL_STR: ABILITY_ENUMS.roll,
    SHOCK_JUMP_STR: ABILITY_ENUMS.shock_jump,
    STILT_STRIDE_STR: ABILITY_ENUMS.stilt_stride,
    DIVE_STR: ABILITY_ENUMS.dive,
    TALON_TROT_STR: ABILITY_ENUMS.talon_trot,
    TURBO_TALON_TROT_STR: ABILITY_ENUMS.turbo_talon_trot,
    WONDERWING_STR: ABILITY_ENUMS.wonderwing,
    NOTE_DOOR_STR: ABILITY_ENUMS.note_door,
}