ORIGINAL_ROM_PATH_STR:str = "Original ROM Path"
NEW_ROM_PATH_STR:str = "New ROM Path"
# Quality Of Life
BOOT_TO_FILE_SELECT_STR:str = "Boot To File Select"
SKIPPABLE_CUTSCENES_STR:str = "Skippable Cutscenes"
SKIP_JIGGY_JIG_STR:str = "Skip Jiggy Jig"
# Difficulty
STARTING_BLUE_EGG_COUNT_STR:str = "Starting Blue Egg Count"
STARTING_RED_FEATHER_COUNT_STR:str = "Starting Red Feather Count"
STARTING_GOLD_FEATHER_COUNT_STR:str = "Starting Gold Feather Count"
STARTING_MUMBO_TOKEN_COUNT_STR:str = "Starting Mumbo Token Count"
ENABLE_FALLPROOF_STR:str = "Enable Fallproof"
# Logic
SELECT_STARTING_MOVES_STR:str = "Select Starting Moves"
BEAK_BARGE_STR:str = "Beak Barge"
BEAK_BOMB_STR:str = "Beak Bomb"
BEAK_BUSTER_STR:str = "Beak Buster"
CLAW_SWIPE_STR:str = "Claw Swipe"
CLIMB_STR:str = "Climb"
EGG_FIRING_STR:str = "Egg Firing"
FEATHERY_FLAP_STR:str = "Feathery Flap"
FLAP_FLIP_STR:str = "Flap Flip"
FLIGHT_STR:str = "Flight"
HIGH_JUMP_STR:str = "High Jump"
RAT_A_TAP_RAP_STR:str = "Rat-A-Tap Rap"
ROLL_STR:str = "Roll"
SHOCK_JUMP_STR:str = "Shock Jump"
STILT_STRIDE_STR:str = "Stilt Stride"
DIVE_STR:str = "Dive"
TALON_TROT_STR:str = "Talon Trot"
TURBO_TALON_TROT_STR:str = "Turbo Talon Trot"
WONDERWING_STR:str = "Wonderwing"
NOTE_DOOR_STR:str = "Note Door"
SHOCK_JUMP_PAD_ANYWHERE_STR:str = "Shock Jump Pad Anywhere"