ORIGINAL_ROM_PATH_STR:str = "Original ROM Path"
NEW_ROM_PATH_STR:str = "New ROM Path"
# Quality Of Life
BOOT_TO_FILE_SELECT_STR:str = "Boot To File Select"
SKIPPABLE_CUTSCENES_STR:str = "Skippable Cutscenes"
SKIP_JIGGY_JIG_STR:str = "Skip Jiggy Jig"
# Difficulty
STARTING_BLUE_EGG_COUNT_STR:str = "Starting Blue Egg Count"
STARTING_RED_FEATHER_COUNT_STR:str = "Starting Red Feather Count"
STARTING_GOLD_FEATHER_COUNT_STR:str = "Starting Gold Feather Count"
STARTING_MUMBO_TOKEN_COUNT_STR:str = "Starting Mumbo Token Count"
ENABLE_FALLPROOF_STR:str = "Enable Fallproof"
# Logic
SELECT_STARTING_MOVES_STR:str = "Select Starting Moves"
BEAK_BARGE_STR:str = "Beak Barge"
BEAK_BOMB_STR:str = "Beak Bomb"
BEAK_BUSTER_STR:str = "Beak Buster"
CLAW_SWIPE_STR:str = "Claw Swipe"
CLIMB_STR:str = "Climb"
EGG_FIRING_STR:str = "Egg Firing"
FEATHERY_FLAP_STR:str = "Feathery Flap"
FLAP_FLIP_STR:str = "Flap Flip"
FLIGHT_STR:str = "Flight"
HIGH_JUMP_STR:str = "High Jump"
RAT_A_TAP_RAP_STR:str = "Rat-A-Tap Rap"
ROLL_STR:str = "Roll"
SHOCK_JUMP_STR:str = "Shock Jump"
STILT_STRIDE_STR:str = "Stilt Stride"
DIVE_STR:str = "Dive"
TALON_TROT_STR:str = "Talon Trot"
TURBO_TALON_TROT_STR:str = "Turbo Talon Trot"
WONDERWING_STR:str = "Wonderwing"
NOTE_DOOR_STR:str = "Note Door"
SHOCK_JUMP_PAD_ANYWHERE_STR:str = "Shock Jump Pad Anywhere"
ALTERNATE_WIN_CONDITION_STR:str = "Alternate Win Condition"
JIGGY_WIN_CONDITION_STR:str = "Jiggy Win Condition"
NOTE_WIN_CONDITION_STR:str = "Note Win Condition"
TOKEN_WIN_CONDITION_STR:str = "Token Win Condition"
HONEYCOMB_WIN_CONDITION_STR:str = "Honeycomb Win Condition"
# NOTE DOORS
NOTE_DOOR_50_COST_STR:str = "Note Door 50 Cost"
NOTE_DOOR_180_COST_STR:str = "Note Door 180 Cost"
NOTE_DOOR_260_COST_STR:str = "Note Door 260 Cost"
NOTE_DOOR_350_COST_STR:str = "Note Door 350 Cost"
NOTE_DOOR_450_COST_STR:str = "Note Door 450 Cost"
NOTE_DOOR_640_COST_STR:str = "Note Door 640 Cost"
NOTE_DOOR_765_COST_STR:str = "Note Door 765 Cost"
NOTE_DOOR_810_COST_STR:str = "Note Door 810 Cost"
NOTE_DOOR_828_COST_STR:str = "Note Door 828 Cost"
NOTE_DOOR_846_COST_STR:str = "Note Door 846 Cost"
NOTE_DOOR_864_COST_STR:str = "Note Door 864 Cost"
NOTE_DOOR_882_COST_STR:str = "Note Door 882 Cost"
# JIGSAW PUZZLES
JIGSAW_PUZZLE_1_COST_STR:str = "Jigsaw Puzzle 1 Cost"
JIGSAW_PUZZLE_2_COST_STR:str = "Jigsaw Puzzle 2 Cost"
JIGSAW_PUZZLE_3_COST_STR:str = "Jigsaw Puzzle 3 Cost"
JIGSAW_PUZZLE_4_COST_STR:str = "Jigsaw Puzzle 4 Cost"
JIGSAW_PUZZLE_5_COST_STR:str = "Jigsaw Puzzle 5 Cost"
JIGSAW_PUZZLE_6_COST_STR:str = "Jigsaw Puzzle 6 Cost"
JIGSAW_PUZZLE_7_COST_STR:str = "Jigsaw Puzzle 7 Cost"
JIGSAW_PUZZLE_8_COST_STR:str = "Jigsaw Puzzle 8 Cost"
JIGSAW_PUZZLE_9_COST_STR:str = "Jigsaw Puzzle 9 Cost"
JIGSAW_PUZZLE_10_COST_STR:str = "Jigsaw Puzzle 10 Cost"
JIGSAW_PUZZLE_11_COST_STR:str = "Jigsaw Puzzle 11 Cost"
# COSMETICS & SOUNDS
LOW_POLY_MODEL_STR:str = "Low Poly Model"
HIGH_POLY_MODEL_STR:str = "High Poly Model"